name: Configurar Node

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkouts@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install
        
